---
title       : Preditor-Prey Relationship
subtitle    : A Population Case Study
author      : 
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides

--- .class #id bg:#F9B1A4

## Introduction
The relationship between foxes and bunnies (rabbits) can be modeled by the Lotka-Volterra Equations, shown as:


$$\frac{d R}{d t} = \alpha R - \beta R F$$


$$\frac{d F}{d t} = \gamma R F - \delta F$$


Where alpha, beta, gamma, and delta are various parameters used to describe
the growth/death rate of the (R)abbits and (F)oxes.  

The general idea is that fox and rabbit populations depends on one another.  Too many foxes and the rabbit population declines which causes the foxes to go hungry and they die out too.  Too many rabbits and the fox population explodes due to excess food and the cycle repeates.  

This can be a useful tool in determining if the species are over- or under-popluated.

--- .class #id bg:orange

## Goal of Application

The objective of the application is to:

1. Model preditor-prey relationship.
2. Allow user to modify intial conditions and growth/death rates interactively.
3. Based on initial conditions/parameters, determine if the species survive.

--- .class #id bg:yellow

## How to use the Application

The user can modify 4 parameters and change the intial population of the foxes and bunnies.  Default values for bunnies is 10 and foxes is 5.  The sliders are described as follows:

1. The growth/reproduction rate of Bunnies (default = 1)
2. The rate at which Foxes eat Bunnies (default = 0.6)
3. The death rate of the Foxes (default = 2)
4. The growth of the Fox population due to excess food (default = 0.5)

--- .class #id bg:#8DAAE3

## Example Results

Using the default settings (shown on previous slide) of this interactive relationship, how many Bunnies and Foxes remain after 6 years?

```{r}
library(deSolve)
Pars = c(alpha = 1, beta = 0.6, gamma = 2, delta = 0.5) #Set Parameters
State = c(x = 10, y = 5)  #Set initial population
Time = seq(0, 20, by = .05) #Run for 20 years at 0.05 year time steps
out = as.data.frame(ode(func = fun, y = State, parms = Pars, times = Time)) #Solve ODE
names(out) = c("Time", "Bunnies", "Foxes")
out[out[,1]==6,]
```
 
We started with 10 Bunnies and 5 Foxes.  After 6 years there are 3 Bunnies and 7 Foxes. 